services:
  api:
    build:
      context: .
      dockerfile: FreeSpinsGame/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sql
      - redis
    networks:
      - spin-net
    
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "Just_creative_password1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - spin-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - spin-net

networks:
  spin-net:
    driver: bridge
